### ISSUE TITLE
lesson2_1 Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by gusya-soc** [hiouchiy/IntelAI_and_Cloud#3]
`file_list = glob.glob("test/*/*")`
パスが間違いました
`file_lsit = glob.glob("./train_data/test/*/*")`

**Comment by gusya-soc** [comment]
it's on 
> Optional - Additional Training for the Entire Network
>> Fine Tuning the Entire Network

**Comment by gusya-soc** [comment]
もう一つのVM作って実行すると、いけました。
謎ですが、多分私が間違いしました。
失礼しました。

**Comment by hiouchiy** [comment]
@gusya-soc 
Thanks for letting me know. It seems you are not wrong.
I agree with what you mentioned. That path can be thought as an issue. Therefore I fixed it.
